import type { Exercise } from "@/lib/types";

export const animeExercises: Exercise[] = [
  // ===== A1 =====
  {
    id: "an-a1-mc",
    type: "multiple-choice",
    tematica: "anime",
    difficulty: "A1",
    categoryContext: "Naruto",
    grammarTopic: "Verb to be",
    instruction: "Selecciona la opción correcta:",
    sentence: "Naruto ___ a young ninja from the Hidden Leaf Village.",
    options: ["is", "are", "be", "am"],
    correctIndex: 0,
    tip: {
      title: "Subject-Verb Agreement",
      explanation:
        "Use 'is' with third-person singular subjects (he, she, it, Naruto). 'Are' is for plural, 'am' only with 'I'.",
      titleEs: "Concordancia sujeto-verbo",
      explanationEs: "Usá \"is\" con sujetos en tercera persona singular (he, she, it, Naruto). \"Are\" es para plural, \"am\" solo con \"I\".",
    },
  },
  {
    id: "an-a1-wo",
    type: "word-order",
    tematica: "anime",
    difficulty: "A1",
    categoryContext: "Attack on Titan",
    grammarTopic: "Basic sentence structure (SVO)",
    instruction: "Ordena las palabras para formar una oración correcta:",
    shuffledWords: ["Eren", "is", "a", "soldier", "brave"],
    correctOrder: ["Eren", "is", "a", "brave", "soldier"],
    spanishTranslation: "Eren es un soldado valiente.",
tip: {
      title: "Adjective Order",
      explanation:
        "In English, adjectives come before the noun they describe. 'Brave' describes 'soldier', so it goes before it: 'a brave soldier'.",
      titleEs: "Orden de los adjetivos",
      explanationEs: "En inglés, los adjetivos van antes del sustantivo que describen. \"Brave\" describe a \"soldier\", así que va antes: \"a brave soldier\".",
    },
  },
  {
    id: "an-a1-rc",
    type: "reading-comprehension",
    tematica: "anime",
    difficulty: "A1",
    categoryContext: "Pokémon",
    grammarTopic: "Personal Pronouns",
    instruction: "Lee el texto y responde:",
    passage:
      "Ash Ketchum is a Pokémon trainer. He is ten years old. His best friend is Pikachu. Pikachu is a yellow Pokémon. It likes ketchup.",
    questionText: "What does Pikachu like?",
    options: ["Pokéballs", "Ketchup", "Battles", "Water"],
    correctIndex: 1,
    tip: {
      title: "Reading for Details",
      explanation:
        "The text says 'It likes ketchup'. 'It' refers to Pikachu. Always check what pronoun refers to which subject.",
      titleEs: "Lectura de detalles",
      explanationEs: "El texto dice \"It likes ketchup\". \"It\" se refiere a Pikachu. Siempre verificá a qué sujeto se refiere cada pronombre.",
    },
  },
  {
    id: "an-a1-qa",
    type: "question-answer",
    variant: "find-question",
    tematica: "anime",
    difficulty: "A1",
    categoryContext: "Dragon Ball",
    grammarTopic: "Wh- questions with 'who'",
    instruction: "Elige la pregunta que mejor corresponde a esta respuesta:",
    prompt: "Goku is a Saiyan warrior.",
    options: [
      "Who is Goku?",
      "Where is Goku?",
      "What is Goku?",
      "Why is Goku strong?",
    ],
    correctIndex: 2,
    tip: {
      title: "'What' for Identity/Profession",
      explanation:
        "'What is...' asks about someone's identity, role, or profession. The answer identifies Goku as 'a Saiyan warrior', so 'What is Goku?' is the correct question.",
      titleEs: "\"What\" para identidad/profesión",
      explanationEs: "\"What is...\" pregunta por la identidad, rol o profesión de alguien. La respuesta identifica a Goku como \"a Saiyan warrior\".",
    },
  },

  // ===== A2 =====
  {
    id: "an-a2-mc",
    type: "multiple-choice",
    tematica: "anime",
    difficulty: "A2",
    categoryContext: "Naruto",
    grammarTopic: "Present Simple",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "Sasuke ___ to become stronger every day, and Naruto ___ him as his rival.",
    options: [
      "trains / sees",
      "train / see",
      "is training / is seeing",
      "trained / saw",
    ],
    correctIndex: 0,
    tip: {
      title: "Present Simple — Habits and Facts",
      explanation:
        "Present simple describes habits and general truths. 'Every day' signals a routine. Both subjects are third-person singular, so verbs take -s.",
      titleEs: "Presente simple — hábitos y hechos",
      explanationEs: "El presente simple describe hábitos y verdades generales. \"Every day\" indica una rutina. Ambos sujetos son tercera persona singular.",
    },
  },
  {
    id: "an-a2-wo",
    type: "word-order",
    tematica: "anime",
    difficulty: "A2",
    categoryContext: "Demon Slayer",
    grammarTopic: "Present Continuous",
    instruction: "Ordena las palabras para formar una oración correcta:",
    shuffledWords: [
      "Tanjiro",
      "is",
      "fighting",
      "a",
      "demon",
      "right",
      "now",
    ],
    correctOrder: ["Tanjiro", "is", "fighting", "a", "demon", "right", "now"],
    spanishTranslation: "Tanjiro esta luchando contra un demonio ahora mismo.",
tip: {
      title: "Present Continuous Structure",
      explanation:
        "Subject + be + verb-ing + object + time expression. 'Right now' signals an action happening at this moment.",
      titleEs: "Estructura del presente continuo",
      explanationEs: "Sujeto + be + verbo-ing + objeto + expresión de tiempo. \"Right now\" indica una acción que está ocurriendo en este momento.",
    },
  },
  {
    id: "an-a2-rc",
    type: "reading-comprehension",
    tematica: "anime",
    difficulty: "A2",
    categoryContext: "Spy x Family",
    grammarTopic: "There is / There are",
    instruction: "Lee el texto y responde:",
    passage:
      "The Forger family is very unusual. There is a spy, an assassin, and a telepath in the family, but nobody knows each other's secrets. There are many funny moments when they try to act like a normal family. There is also a dog named Bond who can see the future.",
    questionText: "How many members of the Forger family have special abilities?",
    options: ["One", "Two", "Three", "Four"],
    correctIndex: 3,
    tip: {
      title: "Counting Details in a Text",
      explanation:
        "Count carefully: Loid (spy), Yor (assassin), Anya (telepath), and Bond the dog (sees the future). That's four characters with special abilities.",
      titleEs: "Contando detalles en un texto",
      explanationEs: "Contá con cuidado: Loid (espía), Yor (asesina), Anya (telépata) y Bond el perro (ve el futuro). Son cuatro personajes con habilidades especiales.",
    },
  },
  {
    id: "an-a2-qa",
    type: "question-answer",
    variant: "find-answer",
    tematica: "anime",
    difficulty: "A2",
    categoryContext: "Sailor Moon",
    grammarTopic: "Short answers",
    instruction: "Elige la mejor respuesta para esta pregunta:",
    prompt: "Can Usagi transform into Sailor Moon without her brooch?",
    options: [
      "No, she needs her transformation brooch.",
      "Yes, she likes the moon.",
      "No, she is a student.",
      "Yes, she has blonde hair.",
    ],
    correctIndex: 0,
    tip: {
      title: "Relevant Yes/No Answers",
      explanation:
        "A logical answer to 'Can...?' should respond directly to the ability question. Only 'No, she needs...' gives a proper reason connected to the question.",
      titleEs: "Respuestas de sí/no relevantes",
      explanationEs: "Una respuesta lógica a \"Can...?\" debe responder directamente a la pregunta de habilidad. Solo \"No, she needs...\" da una razón conectada con la pregunta.",
    },
  },

  // ===== B1 =====
  {
    id: "an-b1-mc",
    type: "multiple-choice",
    tematica: "anime",
    difficulty: "B1",
    categoryContext: "Attack on Titan",
    grammarTopic: "Past Simple",
    instruction: "Selecciona la opción correcta:",
    sentence: "The Survey Corps ___ beyond the walls many times last year.",
    options: ["ventured", "was venturing", "had ventured", "ventures"],
    correctIndex: 0,
    tip: {
      title: "Past Simple for Completed Events",
      explanation:
        "Past simple for finished past actions. 'Last year' is a completed time period, so 'ventured' (past simple) is correct.",
      titleEs: "Pasado simple para eventos completados",
      explanationEs: "Pasado simple para acciones terminadas en el pasado. \"Last year\" es un período de tiempo completado, así que \"ventured\" es correcto.",
    },
  },
  {
    id: "an-b1-wo",
    type: "word-order",
    tematica: "anime",
    difficulty: "B1",
    categoryContext: "Fullmetal Alchemist",
    grammarTopic: "Past Simple questions",
    instruction: "Ordena las palabras para formar una pregunta correcta:",
    shuffledWords: [
      "did",
      "Edward",
      "and",
      "Alphonse",
      "try",
      "to",
      "bring",
      "their",
      "mother",
      "back",
      "?",
    ],
    correctOrder: [
      "did",
      "Edward",
      "and",
      "Alphonse",
      "try",
      "to",
      "bring",
      "their",
      "mother",
      "back",
      "?",
    ],
    spanishTranslation: "Intentaron Edward y Alphonse traer de vuelta a su madre?",
tip: {
      title: "Past Simple Questions — Compound Subjects",
      explanation:
        "For past simple questions with compound subjects, use 'Did + [subject 1 + and + subject 2] + base verb'. The auxiliary 'did' handles the tense.",
      titleEs: "Preguntas en pasado simple — sujetos compuestos",
      explanationEs: "Para preguntas con sujetos compuestos, usá \"Did + [sujeto 1 + and + sujeto 2] + verbo base\". El auxiliar \"did\" maneja el tiempo.",
    },
  },
  {
    id: "an-b1-rc",
    type: "reading-comprehension",
    tematica: "anime",
    difficulty: "B1",
    categoryContext: "Studio Ghibli",
    grammarTopic: "Connectors (because, so, although)",
    instruction: "Lee el texto y responde:",
    passage:
      "Spirited Away is often considered Hayao Miyazaki's masterpiece. Although the film was released in 2001, its animation quality remains stunning by today's standards. The story follows Chihiro, a young girl who enters a spirit world after her parents are turned into pigs. Because she is brave and resourceful, she manages to save them. The film teaches us that courage and kindness can overcome even the most frightening challenges.",
    questionText: "Why does Chihiro manage to save her parents?",
    options: [
      "Because the spirit world is small",
      "Because she is brave and resourceful",
      "Although the film is old",
      "So she can go home",
    ],
    correctIndex: 1,
    tip: {
      title: "Cause and Effect with 'Because'",
      explanation:
        "'Because' introduces a reason. The text says 'Because she is brave and resourceful, she manages to save them.' The reason comes right after 'because'.",
      titleEs: "Causa y efecto con \"Because\"",
      explanationEs: "\"Because\" introduce una razón. El texto dice \"Because she is brave and resourceful, she manages to save them\".",
    },
  },
  {
    id: "an-b1-qa",
    type: "question-answer",
    variant: "find-question",
    tematica: "anime",
    difficulty: "B1",
    categoryContext: "One Punch Man",
    grammarTopic: "Why questions",
    instruction: "Elige la pregunta que mejor corresponde a esta respuesta:",
    prompt:
      "Saitama became a hero for fun, not for fame or money.",
    options: [
      "Why did Saitama become a hero?",
      "How did Saitama become a hero?",
      "When did Saitama become a hero?",
      "Where did Saitama become a hero?",
    ],
    correctIndex: 0,
    tip: {
      title: "Questions of Purpose with 'Why'",
      explanation:
        "'Why' asks about reason or purpose. The answer gives Saitama's motivation ('for fun'), so the question must begin with 'Why'.",
      titleEs: "Preguntas de propósito con \"Why\"",
      explanationEs: "\"Why\" pregunta por razón o propósito. La respuesta da la motivación de Saitama (\"for fun\"), así que la pregunta debe empezar con \"Why\".",
    },
  },

  // ===== B2 =====
  {
    id: "an-b2-mc",
    type: "multiple-choice",
    tematica: "anime",
    difficulty: "B2",
    categoryContext: "Your Name",
    grammarTopic: "Present Perfect",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "Mitsuha and Taki ___ each other's lives for weeks, but they ___ in person yet.",
    options: [
      "have been living / haven't met",
      "lived / didn't meet",
      "are living / aren't meeting",
      "were living / hadn't met",
    ],
    correctIndex: 0,
    tip: {
      title: "Present Perfect Continuous + Present Perfect",
      explanation:
        "Present perfect continuous (have been living) for an ongoing action. Present perfect with 'yet' for something that hasn't happened up to now.",
      titleEs: "Presente perfecto continuo + presente perfecto",
      explanationEs: "Presente perfecto continuo (have been living) para una acción en curso. Presente perfecto con \"yet\" para algo que no ha pasado hasta ahora.",
    },
  },
  {
    id: "an-b2-wo",
    type: "word-order",
    tematica: "anime",
    difficulty: "B2",
    categoryContext: "Steins;Gate",
    grammarTopic: "Second Conditional",
    instruction: "Ordena las palabras para formar una oración correcta:",
    shuffledWords: [
      "If",
      "Okabe",
      "could",
      "travel",
      "back",
      "in",
      "time",
      "he",
      "would",
      "save",
      "Mayuri",
    ],
    correctOrder: [
      "If",
      "Okabe",
      "could",
      "travel",
      "back",
      "in",
      "time",
      "he",
      "would",
      "save",
      "Mayuri",
    ],
    spanishTranslation: "Si Okabe pudiera viajar atras en el tiempo, salvara a Mayuri.",
tip: {
      title: "Second Conditional Structure",
      explanation:
        "If + past simple (or 'could'), would + base verb. Second conditional describes imaginary or unlikely situations.",
      titleEs: "Estructura del segundo condicional",
      explanationEs: "If + pasado simple (o \"could\"), would + verbo base. El segundo condicional describe situaciones imaginarias o poco probables.",
    },
  },
  {
    id: "an-b2-rc",
    type: "reading-comprehension",
    tematica: "anime",
    difficulty: "B2",
    categoryContext: "Vinland Saga",
    grammarTopic: "Contrast connectors (however, whereas)",
    instruction: "Lee el texto y responde:",
    passage:
      "Thorfinn begins his journey consumed by revenge, dedicating every waking moment to avenging his father's death. His obsession with killing Askeladd defines his entire youth. However, after witnessing the futility of violence firsthand, Thorfinn undergoes a profound transformation. Whereas he once believed that strength meant the ability to destroy, he eventually concludes that true strength lies in creating and protecting. His journey from warrior to pacifist represents one of anime's most compelling character arcs.",
    questionText:
      "How does Thorfinn's understanding of strength change throughout the story?",
    options: [
      "He stops believing in strength entirely",
      "He shifts from seeing strength as destruction to seeing it as creation and protection",
      "He believes strength only matters in battle",
      "He decides that strength is irrelevant to his life",
    ],
    correctIndex: 1,
    tip: {
      title: "Tracing Character Development",
      explanation:
        "'Whereas' introduces a contrast between past and present beliefs. The text contrasts his old view (strength = destroying) with his new view (strength = creating/protecting).",
      titleEs: "Trazando el desarrollo de un personaje",
      explanationEs: "\"Whereas\" introduce un contraste entre creencias pasadas y presentes. El texto contrasta su vieja visión (fuerza = destruir) con su nueva visión (fuerza = crear/proteger).",
    },
  },
  {
    id: "an-b2-qa",
    type: "question-answer",
    variant: "find-answer",
    tematica: "anime",
    difficulty: "B2",
    categoryContext: "Attack on Titan",
    grammarTopic: "Expressing certainty and doubt",
    instruction: "Elige la mejor respuesta para esta pregunta:",
    prompt:
      "Do you believe Eren's actions in the final season were justified?",
    options: [
      "It's a morally complex question — while his desire to protect his people is understandable, the scale of destruction he unleashed makes it nearly impossible to fully justify.",
      "Eren is the main character of Attack on Titan.",
      "The final season has many episodes.",
      "I watched it on Crunchyroll.",
    ],
    correctIndex: 0,
    tip: {
      title: "Balanced Opinion Responses",
      explanation:
        "When a question involves moral complexity, a good answer acknowledges both sides before reaching a conclusion. This demonstrates critical thinking in English.",
      titleEs: "Respuestas de opinión balanceadas",
      explanationEs: "Cuando una pregunta implica complejidad moral, una buena respuesta reconoce ambos lados antes de llegar a una conclusión.",
    },
  },

  // ===== C1 =====
  {
    id: "an-c1-mc",
    type: "multiple-choice",
    tematica: "anime",
    difficulty: "C1",
    categoryContext: "Cowboy Bebop",
    grammarTopic: "Past Perfect Continuous",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "Spike ___ from the Syndicate for years before he finally ___ Julia again.",
    options: [
      "had been running / saw",
      "ran / had seen",
      "was running / sees",
      "has been running / had seen",
    ],
    correctIndex: 0,
    tip: {
      title: "Past Perfect Continuous — Duration Before Another Event",
      explanation:
        "Past perfect continuous (had been + -ing) emphasizes the duration of an action BEFORE another past event. Running (ongoing) preceded seeing Julia (point event).",
      titleEs: "Pasado perfecto continuo — duración antes de otro evento",
      explanationEs: "El pasado perfecto continuo (had been + -ing) enfatiza la duración de una acción ANTES de otro evento pasado. Huir (en curso) precedió a ver a Julia (evento puntual).",
    },
  },
  {
    id: "an-c1-wo",
    type: "word-order",
    tematica: "anime",
    difficulty: "C1",
    categoryContext: "Studio Ghibli",
    grammarTopic: "Passive Voice (Present Perfect)",
    instruction: "Ordena las palabras para formar una oración en voz pasiva:",
    shuffledWords: [
      "Spirited",
      "Away",
      "has",
      "been",
      "praised",
      "by",
      "critics",
      "worldwide",
    ],
    correctOrder: [
      "Spirited",
      "Away",
      "has",
      "been",
      "praised",
      "by",
      "critics",
      "worldwide",
    ],
    spanishTranslation: "El Viaje de Chihiro ha sido alabado por la critica mundial.",
tip: {
      title: "Present Perfect Passive",
      explanation:
        "Has/have + been + past participle. The focus is on Spirited Away receiving praise, not on the critics who praised it.",
      titleEs: "Pasiva en presente perfecto",
      explanationEs: "Has/have + been + participio pasado. El foco está en que El Viaje de Chihiro recibe elogios, no en quiénes lo elogiaron.",
    },
  },
  {
    id: "an-c1-rc",
    type: "reading-comprehension",
    tematica: "anime",
    difficulty: "C1",
    categoryContext: "Monster",
    grammarTopic: "Author's Tone and Purpose",
    instruction: "Lee el texto y responde:",
    passage:
      "Naoki Urasawa's Monster is less a thriller about a serial killer and more a philosophical inquiry into the nature of evil. Dr. Tenma's journey across post-Cold War Germany becomes a meditation on moral responsibility: are we accountable for the monsters we create? The narrative refuses easy answers, instead forcing the reader to sit with uncomfortable questions about guilt, redemption, and whether some people are simply beyond saving. In this sense, Monster transcends its genre — it is not merely asking 'who is the killer?' but 'what makes a killer?'",
    questionText:
      "What is the author's main argument about Monster's narrative purpose?",
    options: [
      "It is primarily an exciting thriller about catching a killer",
      "It uses the thriller format as a vehicle for philosophical questions about evil and responsibility",
      "It is a historical account of post-Cold War Germany",
      "It is a simple story about a doctor saving lives",
    ],
    correctIndex: 1,
    tip: {
      title: "Identifying Author's Purpose",
      explanation:
        "The author explicitly states Monster is 'less a thriller... and more a philosophical inquiry'. The phrase 'transcends its genre' confirms the deeper purpose beyond entertainment.",
      titleEs: "Identificando el propósito del autor",
      explanationEs: "El autor dice explícitamente que Monster es \"menos un thriller... y más una investigación filosófica\". La frase \"trasciende su género\" confirma el propósito más profundo.",
    },
  },
  {
    id: "an-c1-qa",
    type: "question-answer",
    variant: "find-question",
    tematica: "anime",
    difficulty: "C1",
    categoryContext: "Ghost in the Shell",
    grammarTopic: "Hypothetical questions",
    instruction: "Elige la pregunta que mejor corresponde a esta respuesta:",
    prompt:
      "The Major questions her humanity because her consciousness exists in a fully cybernetic body, blurring the line between human and machine.",
    options: [
      "Under what circumstances would someone's humanity become ambiguous?",
      "How many episodes does Ghost in the Shell have?",
      "Is the Major a good fighter?",
      "What year was Ghost in the Shell released?",
    ],
    correctIndex: 0,
    tip: {
      title: "Matching Abstract Questions to Complex Answers",
      explanation:
        "The answer discusses the philosophical concept of humanity versus machinery. Only the first question, which asks about 'circumstances' where humanity becomes 'ambiguous', matches this level of abstraction.",
      titleEs: "Uniendo preguntas abstractas con respuestas complejas",
      explanationEs: "La respuesta discute el concepto filosófico de humanidad vs. máquina. Solo la primera pregunta, sobre \"circunstancias\" donde la humanidad se vuelve \"ambigua\", coincide con este nivel de abstracción.",
    },
  },

  // ===== C2 =====
  {
    id: "an-c2-mc",
    type: "multiple-choice",
    tematica: "anime",
    difficulty: "C2",
    categoryContext: "Neon Genesis Evangelion",
    grammarTopic: "Subjunctive Mood",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "It is essential that every Eva pilot ___ a psychological evaluation before synchronization.",
    options: ["undergo", "undergoes", "will undergo", "underwent"],
    correctIndex: 0,
    tip: {
      title: "Subjunctive after 'It is essential that...'",
      explanation:
        "After expressions like 'it is essential/important/necessary that...', use the subjunctive mood: the base form of the verb (undergo), regardless of the subject.",
      titleEs: "Subjuntivo después de \"It is essential that...\"",
      explanationEs: "Después de expresiones como \"it is essential/important/necessary that...\", usá el modo subjuntivo: la forma base del verbo (undergo), sin importar el sujeto.",
    },
  },
  {
    id: "an-c2-wo",
    type: "word-order",
    tematica: "anime",
    difficulty: "C2",
    categoryContext: "Death Note",
    grammarTopic: "Advanced cleft sentences",
    instruction: "Ordena las palabras para formar una oración enfática:",
    shuffledWords: [
      "What",
      "Light",
      "Yagami",
      "failed",
      "to",
      "understand",
      "was",
      "that",
      "absolute",
      "power",
      "corrupts",
      "absolutely",
    ],
    correctOrder: [
      "What",
      "Light",
      "Yagami",
      "failed",
      "to",
      "understand",
      "was",
      "that",
      "absolute",
      "power",
      "corrupts",
      "absolutely",
    ],
    spanishTranslation: "Lo que Light Yagami no logro entender fue que el poder absoluto corrompe absolutamente.",
tip: {
      title: "Wh- Cleft Sentences",
      explanation:
        "'What + clause + was + that + clause' emphasizes the thing that was not understood. This structure is more emphatic than 'Light didn't understand that...'",
      titleEs: "Oraciones enfáticas con \"Wh-\"",
      explanationEs: "\"What + cláusula + was + that + cláusula\" enfatiza lo que no se entendió. Esta estructura es más enfática que \"Light didn't understand that...\"",
    },
  },
  {
    id: "an-c2-rc",
    type: "reading-comprehension",
    tematica: "anime",
    difficulty: "C2",
    categoryContext: "Serial Experiments Lain",
    grammarTopic: "Critical Analysis",
    instruction: "Lee el texto y responde:",
    passage:
      "Serial Experiments Lain was remarkably prescient. Released in 1998, years before social media reshaped human interaction, the series interrogated the boundaries between physical and digital identity with an acuity that has only grown more relevant. Lain's fragmentation across the Wired — existing simultaneously as a shy schoolgirl and an omnipotent digital entity — anticipated the curated, multiplicitous selves we now maintain across platforms. The series' central anxiety was not that technology would destroy humanity, but that it would dissolve the very concept of a coherent self, rendering the question 'who am I?' both urgent and unanswerable.",
    questionText:
      "According to the passage, what made Serial Experiments Lain 'prescient'?",
    options: [
      "It predicted specific social media platforms",
      "It explored digital identity fragmentation long before social media made it a widespread reality",
      "It was the first anime about technology",
      "It accurately forecast the year social media would be invented",
    ],
    correctIndex: 1,
    tip: {
      title: "Understanding 'Prescience' in Critical Writing",
      explanation:
        "'Prescient' means having knowledge of events before they happen. The passage explains the series anticipated ('years before') how people would maintain multiple digital identities ('curated, multiplicitous selves').",
      titleEs: "Entendiendo \"prescience\" en escritura crítica",
      explanationEs: "\"Prescient\" significa tener conocimiento de eventos antes de que ocurran. El pasaje explica que la serie anticipó (\"años antes\") cómo la gente mantendría múltiples identidades digitales.",
    },
  },
  {
    id: "an-c2-qa",
    type: "question-answer",
    variant: "find-answer",
    tematica: "anime",
    difficulty: "C2",
    categoryContext: "Studio Ghibli",
    grammarTopic: "Sophisticated argumentation",
    instruction: "Elige la mejor respuesta para esta pregunta:",
    prompt:
      "To what extent do you believe Miyazaki's environmental themes are didactic rather than narrative?",
    options: [
      "While the ecological messaging is unmistakable, Miyazaki embeds it so organically into his world-building that it rarely feels preachy — the pollution in Princess Mononoke serves the plot as much as the polemic, which is arguably why his films persuade where documentaries merely inform.",
      "Miyazaki makes movies about nature.",
      "I think his films are very pretty and the animation is good.",
      "Princess Mononoke has forest spirits in it.",
    ],
    correctIndex: 0,
    tip: {
      title: "C2-Level Argumentation",
      explanation:
        "At the highest proficiency level, responses should engage with the premise (didactic vs. narrative), use precise vocabulary ('embeds', 'polemic'), and make a comparative claim supported by specific evidence.",
      titleEs: "Argumentación de nivel C2",
      explanationEs: "En el nivel más alto, las respuestas deben involucrarse con la premisa (didáctico vs. narrativo), usar vocabulario preciso y hacer una afirmación comparativa respaldada por evidencia específica.",
    },
  },
];
