import type { Exercise } from "@/lib/types";

export const historiaExercises: Exercise[] = [
  // ===== A1 =====
  {
    id: "hi-a1-mc",
    type: "multiple-choice",
    tematica: "historia",
    difficulty: "A1",
    categoryContext: "Revolución de Mayo",
    grammarTopic: "Verb to be (past)",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "The May Revolution ___ an important event in Argentine history.",
    options: ["was", "were", "is", "be"],
    correctIndex: 0,
    tip: {
      title: "Past Simple of 'to be'",
      explanation:
        "Use 'was' for singular subjects in the past. 'The May Revolution' is singular, so 'was' is correct.",
      titleEs: "Pasado simple del verbo \"to be\"",
      explanationEs: "Usá \"was\" para sujetos singulares en pasado. \"The May Revolution\" es singular, así que \"was\" es correcto.",
    },
  },
  {
    id: "hi-a1-wo",
    type: "word-order",
    tematica: "historia",
    difficulty: "A1",
    categoryContext: "Guerra de Malvinas",
    grammarTopic: "Basic sentence structure (SVO)",
    instruction: "Ordena las palabras para formar una oración correcta:",
    shuffledWords: [
      "The",
      "Malvinas",
      "Islands",
      "are",
      "in",
      "the",
      "South",
      "Atlantic",
    ],
    correctOrder: [
      "The",
      "Malvinas",
      "Islands",
      "are",
      "in",
      "the",
      "South",
      "Atlantic",
    ],
    spanishTranslation: "Las Islas Malvinas estan en el Atlantico Sur.",
tip: {
      title: "Subject + Verb + Location",
      explanation:
        "English follows Subject-Verb-Complement order: [The Malvinas Islands] + [are] + [in the South Atlantic].",
      titleEs: "Sujeto + Verbo + Ubicación",
      explanationEs: "El inglés sigue el orden Sujeto-Verbo-Complemento: [The Malvinas Islands] + [are] + [in the South Atlantic].",
    },
  },
  {
    id: "hi-a1-rc",
    type: "reading-comprehension",
    tematica: "historia",
    difficulty: "A1",
    categoryContext: "Peronismo",
    grammarTopic: "Personal Pronouns",
    instruction: "Lee el texto y responde:",
    passage:
      "Juan Domingo Perón was a president of Argentina. He was very popular with workers. His wife was Eva Perón, also known as Evita. She helped poor people and fought for women's rights.",
    questionText: "Who helped poor people?",
    options: ["Juan Perón", "Evita", "The workers", "The military"],
    correctIndex: 1,
    tip: {
      title: "Pronoun Reference",
      explanation:
        "'She' in the text refers to Eva Perón (Evita). The sentence 'She helped poor people' tells us Evita is the answer.",
      titleEs: "Referencia de pronombres",
      explanationEs: "\"She\" en el texto se refiere a Eva Perón (Evita). La oración \"She helped poor people\" nos dice que Evita es la respuesta.",
    },
  },
  {
    id: "hi-a1-qa",
    type: "question-answer",
    variant: "find-question",
    tematica: "historia",
    difficulty: "A1",
    categoryContext: "Dictadura militar",
    grammarTopic: "Wh- questions with 'when'",
    instruction: "Elige la pregunta que mejor corresponde a esta respuesta:",
    prompt: "The military dictatorship ended in 1983.",
    options: [
      "When did the military dictatorship end?",
      "Why did the military dictatorship end?",
      "Who ended the military dictatorship?",
      "What was the military dictatorship?",
    ],
    correctIndex: 0,
    tip: {
      title: "'When' for Time Questions",
      explanation:
        "Use 'when' to ask about time. The answer gives a year (1983), so the question must begin with 'When'.",
      titleEs: "\"When\" para preguntas de tiempo",
      explanationEs: "Usá \"when\" para preguntar sobre tiempo. La respuesta da un año (1983), así que la pregunta debe empezar con \"When\".",
    },
  },

  // ===== A2 =====
  {
    id: "hi-a2-mc",
    type: "multiple-choice",
    tematica: "historia",
    difficulty: "A2",
    categoryContext: "Inmigración",
    grammarTopic: "Present Simple",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "Many Argentines ___ their ancestry to Italian and Spanish immigrants who ___ in the late 19th century.",
    options: ["trace / arrived", "traces / arrive", "are tracing / arriving", "traced / arrives"],
    correctIndex: 0,
    tip: {
      title: "Present Simple — General Truths",
      explanation:
        "'Trace' is a general fact about Argentines today. 'Arrived' is past simple because the immigration happened in the past. 'Many Argentines' is plural, so 'trace' has no -s.",
      titleEs: "Presente simple — verdades generales",
      explanationEs: "\"Trace\" es un hecho general sobre los argentinos hoy. \"Arrived\" está en pasado simple porque la inmigración ocurrió en el pasado.",
    },
  },
  {
    id: "hi-a2-wo",
    type: "word-order",
    tematica: "historia",
    difficulty: "A2",
    categoryContext: "Peronismo",
    grammarTopic: "There was / There were",
    instruction: "Ordena las palabras para formar una oración correcta:",
    shuffledWords: [
      "there",
      "were",
      "many",
      "social",
      "reforms",
      "during",
      "Perón's",
      "first",
      "presidency",
    ],
    correctOrder: [
      "there",
      "were",
      "many",
      "social",
      "reforms",
      "during",
      "Perón's",
      "first",
      "presidency",
    ],
    spanishTranslation: "Hubo muchas reformas sociales durante la primera presidencia de Peron.",
tip: {
      title: "'There were' for Plural Nouns",
      explanation:
        "Use 'there were' (not 'there was') with plural nouns. 'Many social reforms' is plural, so 'there were' is correct.",
      titleEs: "\"There were\" para sustantivos plurales",
      explanationEs: "Usá \"there were\" (no \"there was\") con sustantivos plurales. \"Many social reforms\" es plural, así que \"there were\" es correcto.",
    },
  },
  {
    id: "hi-a2-rc",
    type: "reading-comprehension",
    tematica: "historia",
    difficulty: "A2",
    categoryContext: "Guerra de Malvinas",
    grammarTopic: "Can / Could",
    instruction: "Lee el texto y responde:",
    passage:
      "The Falklands War took place in 1982 between Argentina and the United Kingdom. Argentina could not use all of its military resources because of international sanctions. The British navy could travel long distances to reach the islands. After 74 days, Argentina surrendered.",
    questionText: "Why could the British navy reach the Malvinas Islands?",
    options: [
      "Because the islands were very close to the UK",
      "Because the British navy could travel long distances",
      "Because Argentina helped them",
      "Because the war was short",
    ],
    correctIndex: 1,
    tip: {
      title: "Using 'could' for Past Ability",
      explanation:
        "'Could' expresses past ability. The text says 'The British navy could travel long distances', explaining how they reached the islands.",
      titleEs: "Usando \"could\" para habilidad pasada",
      explanationEs: "\"Could\" expresa habilidad pasada. El texto dice \"The British navy could travel long distances\", explicando cómo llegaron a las islas.",
    },
  },
  {
    id: "hi-a2-qa",
    type: "question-answer",
    variant: "find-answer",
    tematica: "historia",
    difficulty: "A2",
    categoryContext: "Dictadura militar",
    grammarTopic: "Short answers in past tense",
    instruction: "Elige la mejor respuesta para esta pregunta:",
    prompt: "Did the military government respect human rights?",
    options: [
      "No, it committed serious human rights violations.",
      "Yes, it was a democratic government.",
      "No, it started in 1976.",
      "Yes, it lasted until 1983.",
    ],
    correctIndex: 0,
    tip: {
      title: "Logical Short Answers",
      explanation:
        "A proper answer to 'Did...?' must address the question asked. Only 'No, it committed...' directly answers whether human rights were respected.",
      titleEs: "Respuestas cortas lógicas",
      explanationEs: "Una respuesta adecuada a \"Did...?\" debe responder a la pregunta hecha. Solo \"No, it committed...\" responde directamente si se respetaron los derechos humanos.",
    },
  },

  // ===== B1 =====
  {
    id: "hi-b1-mc",
    type: "multiple-choice",
    tematica: "historia",
    difficulty: "B1",
    categoryContext: "Inmigración",
    grammarTopic: "Past Simple",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "Millions of Europeans ___ to Argentina between 1880 and 1930, and they ___ the country's culture forever.",
    options: ["immigrated / changed", "immigrate / change", "were immigrating / were changing", "had immigrated / changed"],
    correctIndex: 0,
    tip: {
      title: "Past Simple for Historical Events",
      explanation:
        "Both actions are completed past events. The time period 'between 1880 and 1930' confirms past simple. Both clauses tell finished facts.",
      titleEs: "Pasado simple para eventos históricos",
      explanationEs: "Ambas acciones son eventos pasados completados. El período \"between 1880 and 1930\" confirma el pasado simple.",
    },
  },
  {
    id: "hi-b1-wo",
    type: "word-order",
    tematica: "historia",
    difficulty: "B1",
    categoryContext: "Peronismo",
    grammarTopic: "Past Simple questions",
    instruction: "Ordena las palabras para formar una pregunta correcta:",
    shuffledWords: [
      "did",
      "Evita",
      "fight",
      "for",
      "women's",
      "rights",
      "?",
    ],
    correctOrder: ["did", "Evita", "fight", "for", "women's", "rights", "?"],
    spanishTranslation: "Lucho Evita por los derechos de las mujeres?",
tip: {
      title: "Past Simple Yes/No Questions",
      explanation:
        "For past simple questions, use 'Did + subject + base verb'. The auxiliary 'did' carries the tense, so 'fight' stays in base form.",
      titleEs: "Preguntas de sí/no en pasado simple",
      explanationEs: "Para preguntas en pasado simple, usá \"Did + sujeto + verbo base\". El auxiliar \"did\" lleva el tiempo, así que \"fight\" se mantiene en forma base.",
    },
  },
  {
    id: "hi-b1-rc",
    type: "reading-comprehension",
    tematica: "historia",
    difficulty: "B1",
    categoryContext: "Guerra de Malvinas",
    grammarTopic: "Reason and Result (so... that)",
    instruction: "Lee el texto y responde:",
    passage:
      "The Malvinas War was so short that many people were surprised by its quick end. The conflict lasted only 74 days, from April to June 1982. However, its consequences were so significant that they changed Argentine politics for decades. The military government lost so much credibility after the defeat that democratic elections were held the following year.",
    questionText:
      "What was one major consequence of the Malvinas War mentioned in the text?",
    options: [
      "Argentina became a British colony",
      "The military lost credibility and democratic elections followed",
      "The war continued for many years",
      "The islands became independent",
    ],
    correctIndex: 1,
    tip: {
      title: "Cause and Effect with 'so... that'",
      explanation:
        "'So... that' shows an extreme cause leading to a result. The loss of credibility (cause) led to democratic elections (effect).",
      titleEs: "Causa y efecto con \"so... that\"",
      explanationEs: "\"So... that\" muestra una causa extrema que lleva a un resultado. La pérdida de credibilidad (causa) llevó a elecciones democráticas (efecto).",
    },
  },
  {
    id: "hi-b1-qa",
    type: "question-answer",
    variant: "find-question",
    tematica: "historia",
    difficulty: "B1",
    categoryContext: "Inmigración",
    grammarTopic: "What questions for definitions",
    instruction: "Elige la pregunta que mejor corresponde a esta respuesta:",
    prompt:
      "The 'Conventillos' were overcrowded tenement houses where many immigrants lived in Buenos Aires.",
    options: [
      "What were the 'conventillos'?",
      "Where were the 'conventillos'?",
      "Why did immigrants live in 'conventillos'?",
      "How many 'conventillos' were there?",
    ],
    correctIndex: 0,
    tip: {
      title: "'What' for Definitions",
      explanation:
        "The answer defines what 'conventillos' were. A 'What were...?' question asks for a definition, which is exactly what the answer provides.",
      titleEs: "\"What\" para definiciones",
      explanationEs: "La respuesta define qué eran los \"conventillos\". Una pregunta con \"What were...?\" pide una definición, que es justo lo que la respuesta proporciona.",
    },
  },

  // ===== B2 =====
  {
    id: "hi-b2-mc",
    type: "multiple-choice",
    tematica: "historia",
    difficulty: "B2",
    categoryContext: "Dictadura militar",
    grammarTopic: "Present Perfect",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "Argentina ___ the wounds of the dictatorship for decades, and the search for justice ___.",
    options: [
      "has been healing / continues",
      "healed / continued",
      "was healing / is continuing",
      "heals / has continued",
    ],
    correctIndex: 0,
    tip: {
      title: "Present Perfect Continuous + Present Simple",
      explanation:
        "Present perfect continuous (has been healing) for an ongoing process that started in the past. Present simple (continues) for the current state of affairs.",
      titleEs: "Presente perfecto continuo + presente simple",
      explanationEs: "Presente perfecto continuo (has been healing) para un proceso en curso que empezó en el pasado. Presente simple (continues) para el estado actual.",
    },
  },
  {
    id: "hi-b2-wo",
    type: "word-order",
    tematica: "historia",
    difficulty: "B2",
    categoryContext: "Peronismo",
    grammarTopic: "First Conditional",
    instruction: "Ordena las palabras para formar una oración correcta:",
    shuffledWords: [
      "If",
      "you",
      "study",
      "Peronism",
      "you",
      "will",
      "understand",
      "modern",
      "Argentine",
      "politics",
    ],
    correctOrder: [
      "If",
      "you",
      "study",
      "Peronism",
      "you",
      "will",
      "understand",
      "modern",
      "Argentine",
      "politics",
    ],
    spanishTranslation: "Si estudias el peronismo, entenderas la politica argentina moderna.",
tip: {
      title: "First Conditional for Real Possibilities",
      explanation:
        "If + present simple, will + base verb. This expresses a real, likely outcome of studying Peronism.",
      titleEs: "Primer condicional para posibilidades reales",
      explanationEs: "If + presente simple, will + verbo base. Expresa un resultado real y probable de estudiar el peronismo.",
    },
  },
  {
    id: "hi-b2-rc",
    type: "reading-comprehension",
    tematica: "historia",
    difficulty: "B2",
    categoryContext: "Inmigración",
    grammarTopic: "Contrast (whereas, while)",
    instruction: "Lee el texto y responde:",
    passage:
      "Whereas most South American countries experienced gradual demographic change, Argentina underwent one of the most dramatic population transformations in modern history. Between 1880 and 1930, over six million immigrants arrived — primarily from Italy and Spain. While the United States is often celebrated as the great 'melting pot', Argentina actually received more immigrants relative to its existing population. By 1914, nearly 30% of Argentina's residents were foreign-born, a proportion that exceeded even that of the United States at the time. This massive influx reshaped not only the country's demographics but also its language, cuisine, and cultural identity.",
    questionText:
      "What made Argentina's immigration experience unique compared to the United States?",
    options: [
      "Argentina received more immigrants in absolute numbers than the US",
      "Argentina had a higher proportion of foreign-born residents relative to its population",
      "Immigrants only came from Spain to Argentina",
      "Argentina stopped immigration earlier than the US",
    ],
    correctIndex: 1,
    tip: {
      title: "Comparative Reading",
      explanation:
        "The text uses 'whereas' and 'while' to draw contrasts. The key comparison is that Argentina had a HIGHER PROPORTION of immigrants, not higher absolute numbers.",
      titleEs: "Lectura comparativa",
      explanationEs: "El texto usa \"whereas\" y \"while\" para establecer contrastes. La comparación clave es que Argentina tuvo una PROPORCIÓN MAYOR de inmigrantes, no números absolutos más altos.",
    },
  },
  {
    id: "hi-b2-qa",
    type: "question-answer",
    variant: "find-answer",
    tematica: "historia",
    difficulty: "B2",
    categoryContext: "Guerra de Malvinas",
    grammarTopic: "Expressing opinions about history",
    instruction: "Elige la mejor respuesta para esta pregunta:",
    prompt:
      "In your opinion, was the Malvinas War avoidable?",
    options: [
      "Looking back, many historians argue that diplomatic channels were not fully exhausted before the invasion, suggesting the conflict could potentially have been averted through negotiation.",
      "The war happened in 1982.",
      "The islands are also called the Falklands.",
      "Argentina and the UK fought in the war.",
    ],
    correctIndex: 0,
    tip: {
      title: "Supported Historical Opinions",
      explanation:
        "A proper opinion answer uses hedging language ('many historians argue', 'potentially'), references evidence ('diplomatic channels'), and directly addresses the question of avoidability.",
      titleEs: "Opiniones históricas fundamentadas",
      explanationEs: "Una buena respuesta de opinión usa lenguaje de cautela (\"many historians argue\", \"potentially\"), referencia evidencia y responde directamente a la pregunta.",
    },
  },

  // ===== C1 =====
  {
    id: "hi-c1-mc",
    type: "multiple-choice",
    tematica: "historia",
    difficulty: "C1",
    categoryContext: "Dictadura militar",
    grammarTopic: "Past Perfect",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "By the time the 1976 coup took place, political violence ___ dramatically.",
    options: [
      "had escalated",
      "escalated",
      "has escalated",
      "was escalating",
    ],
    correctIndex: 0,
    tip: {
      title: "Past Perfect — Event Before Another Past Event",
      explanation:
        "Past perfect (had + past participle) shows the escalation happened BEFORE the coup. The coup is the reference point in the past; the escalation preceded it.",
      titleEs: "Pasado perfecto — evento anterior a otro evento pasado",
      explanationEs: "El pasado perfecto (had + participio) muestra que la escalada ocurrió ANTES del golpe. El golpe es el punto de referencia en el pasado.",
    },
  },
  {
    id: "hi-c1-wo",
    type: "word-order",
    tematica: "historia",
    difficulty: "C1",
    categoryContext: "Inmigración",
    grammarTopic: "Passive Voice (Past Simple)",
    instruction: "Ordena las palabras para formar una oración en voz pasiva:",
    shuffledWords: [
      "The",
      "Argentine",
      "Constitution",
      "of",
      "1853",
      "was",
      "inspired",
      "by",
      "liberal",
      "ideas",
    ],
    correctOrder: [
      "The",
      "Argentine",
      "Constitution",
      "of",
      "1853",
      "was",
      "inspired",
      "by",
      "liberal",
      "ideas",
    ],
    spanishTranslation: "La Constitucion Argentina de 1853 fue inspirada por ideas liberales.",
tip: {
      title: "Passive Voice — Focus on the Subject",
      explanation:
        "Passive voice (was + past participle) shifts focus to the Constitution rather than who inspired it. Use 'by' to introduce the agent.",
      titleEs: "Voz pasiva — foco en el sujeto",
      explanationEs: "La voz pasiva (was + participio pasado) cambia el foco a la Constitución en lugar de a quién la inspiró. Usá \"by\" para introducir el agente.",
    },
  },
  {
    id: "hi-c1-rc",
    type: "reading-comprehension",
    tematica: "historia",
    difficulty: "C1",
    categoryContext: "Peronismo",
    grammarTopic: "Identifying Bias and Perspective",
    instruction: "Lee el texto y responde:",
    passage:
      "Peronism remains the most contested political movement in Argentine history. To its adherents, it represents social justice, workers' dignity, and national sovereignty. To its detractors, it embodies populist demagoguery, economic mismanagement, and authoritarian tendencies. The truth, as is often the case, resists such binary classification. Perón's first presidency (1946-1952) undeniably expanded labor rights and built infrastructure, yet it also concentrated power in the executive and suppressed dissent. The movement's enduring influence — every Argentine president since 1983 has had to define themselves in relation to Peronism — speaks to its profound, if polarizing, impact on the national psyche.",
    questionText:
      "What is the author's overall perspective on Peronism as presented in this passage?",
    options: [
      "Peronism was entirely negative for Argentina",
      "Peronism was entirely positive for Argentina",
      "Peronism has both positive and negative aspects, and its complexity defies simple categorization",
      "The author refuses to take any position on Peronism",
    ],
    correctIndex: 2,
    tip: {
      title: "Recognizing Balanced Historical Analysis",
      explanation:
        "The author presents both perspectives ('To its adherents... To its detractors...') and then offers a nuanced view ('resists such binary classification'). Words like 'undeniably' and 'yet' signal balanced analysis.",
      titleEs: "Reconociendo un análisis histórico balanceado",
      explanationEs: "El autor presenta ambas perspectivas y luego ofrece una visión matizada (\"resists such binary classification\"). Palabras como \"undeniably\" y \"yet\" señalan un análisis balanceado.",
    },
  },
  {
    id: "hi-c1-qa",
    type: "question-answer",
    variant: "find-question",
    tematica: "historia",
    difficulty: "C1",
    categoryContext: "Dictadura militar",
    grammarTopic: "Complex question formation",
    instruction: "Elige la pregunta que mejor corresponde a esta respuesta:",
    prompt:
      "The 'Madres de Plaza de Mayo' began their protests during the dictatorship by demanding information about their disappeared children, and over time they evolved into a symbol of human rights resistance worldwide.",
    options: [
      "How did the Madres de Plaza de Mayo evolve from a local protest into a global human rights symbol?",
      "When were the Madres de Plaza de Mayo founded?",
      "How many Madres participated in the first protest?",
      "Who led the Madres de Plaza de Mayo?",
    ],
    correctIndex: 0,
    tip: {
      title: "Questions about Evolution and Process",
      explanation:
        "The answer describes a process of transformation ('began... demanding... evolved into...'). A question about 'how' something 'evolved' matches the narrative structure of the response.",
      titleEs: "Preguntas sobre evolución y proceso",
      explanationEs: "La respuesta describe un proceso de transformación (\"began... demanding... evolved into...\"). Una pregunta sobre \"how\" algo \"evolved\" coincide con la estructura narrativa de la respuesta.",
    },
  },

  // ===== C2 =====
  {
    id: "hi-c2-mc",
    type: "multiple-choice",
    tematica: "historia",
    difficulty: "C2",
    categoryContext: "Dictadura militar",
    grammarTopic: "Subjunctive Mood",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "The truth commission recommended that the government ___ full access to all military archives.",
    options: ["grant", "grants", "granted", "will grant"],
    correctIndex: 0,
    tip: {
      title: "Subjunctive after 'recommend that...'",
      explanation:
        "After verbs like 'recommend', 'suggest', 'insist', and 'demand', use the subjunctive: the base form of the verb (grant), regardless of subject.",
      titleEs: "Subjuntivo después de \"recommend that...\"",
      explanationEs: "Después de verbos como \"recommend\", \"suggest\", \"insist\" y \"demand\", usá el subjuntivo: la forma base del verbo (grant), sin importar el sujeto.",
    },
  },
  {
    id: "hi-c2-wo",
    type: "word-order",
    tematica: "historia",
    difficulty: "C2",
    categoryContext: "Guerra de Malvinas",
    grammarTopic: "Advanced cleft sentences",
    instruction: "Ordena las palabras para formar una oración enfática:",
    shuffledWords: [
      "It",
      "was",
      "not",
      "until",
      "the",
      "return",
      "of",
      "democracy",
      "in",
      "1983",
      "that",
      "a",
      "full",
      "accounting",
      "of",
      "the",
      "war",
      "became",
      "possible",
    ],
    correctOrder: [
      "It",
      "was",
      "not",
      "until",
      "the",
      "return",
      "of",
      "democracy",
      "in",
      "1983",
      "that",
      "a",
      "full",
      "accounting",
      "of",
      "the",
      "war",
      "became",
      "possible",
    ],
    spanishTranslation: "No fue hasta el regreso de la democracia en 1983 que un recuento completo de la guerra fue posible.",
tip: {
      title: "'It was not until... that...' Structure",
      explanation:
        "This emphatic structure delays the main point to create dramatic effect. It emphasizes that the accounting was impossible before democracy returned.",
      titleEs: "Estructura \"It was not until... that...\"",
      explanationEs: "Esta estructura enfática retrasa el punto principal para crear efecto dramático. Enfatiza que el recuento fue imposible hasta que la democracia regresó.",
    },
  },
  {
    id: "hi-c2-rc",
    type: "reading-comprehension",
    tematica: "historia",
    difficulty: "C2",
    categoryContext: "Revolución de Mayo",
    grammarTopic: "Rhetorical Analysis",
    instruction: "Lee el texto y responde:",
    passage:
      "To characterize the May Revolution as a sudden rupture with the colonial past is to misunderstand both the nature of revolution and the particularities of the River Plate. The events of May 1810 were neither wholly improvised nor entirely predetermined. They emerged from a confluence of forces — the Napoleonic vacuum in Spain, the British military pressures, and an incipient Creole consciousness that had been fermenting for decades. The Cabildo Abierto of May 22nd was not so much a declaration of independence as it was an improvisation dressed in legalistic form, a provisional solution that, paradoxically, set in motion irreversible transformations. The revolution, in other words, was both made and inherited — a contingent event that drew upon long-gathering structural currents.",
    questionText:
      "What is the author's rhetorical strategy in describing the May Revolution?",
    options: [
      "To argue that the revolution was a complete failure",
      "To deconstruct the simple narrative of 'sudden rupture' by presenting the revolution as both contingent and shaped by long-term forces",
      "To prove that the revolution was entirely planned in advance",
      "To dismiss the importance of the May Revolution entirely",
    ],
    correctIndex: 1,
    tip: {
      title: "Analyzing Rhetorical Strategies",
      explanation:
        "The author uses paradox ('both made and inherited'), negation ('neither wholly improvised nor entirely predetermined'), and redefinition ('not so much X as Y') to complicate a simplistic historical narrative. This is deconstructive rhetorical strategy.",
      titleEs: "Analizando estrategias retóricas",
      explanationEs: "El autor usa paradoja (\"both made and inherited\"), negación (\"neither wholly improvised nor entirely predetermined\") y redefinición (\"not so much X as Y\") para complejizar una narrativa histórica simplista.",
    },
  },
  {
    id: "hi-c2-qa",
    type: "question-answer",
    variant: "find-answer",
    tematica: "historia",
    difficulty: "C2",
    categoryContext: "Peronismo",
    grammarTopic: "Sophisticated argumentation",
    instruction: "Elige la mejor respuesta para esta pregunta:",
    prompt:
      "To what extent can Peronism be understood as a coherent ideology rather than a pragmatic political movement?",
    options: [
      "This question cuts to the heart of Peronism's singularity: it is precisely the movement's capacity to encompass contradictory positions — left and right, nationalist and internationalist, statist and populist — that makes it resistant to ideological classification, yet its core tenets of social justice, economic independence, and political sovereignty have remained remarkably consistent, suggesting it is less an ideology than a political identity flexible enough to absorb competing doctrines.",
      "Peronism is a political party in Argentina.",
      "Perón was president three times.",
      "I think Peronism is interesting to study.",
    ],
    correctIndex: 0,
    tip: {
      title: "C2-Level Historical Argumentation",
      explanation:
        "A sophisticated answer engages with the premise ('coherent ideology vs. pragmatic movement'), acknowledges complexity ('contradictory positions'), and synthesizes a thesis ('less an ideology than a political identity'). This demonstrates historiographical thinking.",
      titleEs: "Argumentación histórica de nivel C2",
      explanationEs: "Una respuesta sofisticada se involucra con la premisa, reconoce complejidad (\"contradictory positions\") y sintetiza una tesis. Esto demuestra pensamiento historiográfico.",
    },
  },
];
