import type { Exercise } from "@/lib/types";

export const videojuegosExercises: Exercise[] = [
  // ===== A1 =====
  {
    id: "vg-a1-mc",
    type: "multiple-choice",
    tematica: "videojuegos",
    difficulty: "A1",
    categoryContext: "The Legend of Zelda",
    grammarTopic: "Verb to be",
    instruction: "Selecciona la opción correcta para completar la oración:",
    sentence: "Link ___ the hero of Hyrule in 'The Legend of Zelda' series.",
    options: ["is", "are", "be", "am"],
    correctIndex: 0,
    tip: {
      title: "Subject-Verb Agreement",
      explanation:
        "Use 'is' with third-person singular subjects (he, she, it, Link). 'Are' is for plural subjects, and 'am' only goes with 'I'.",
      titleEs: "Concordancia sujeto-verbo",
      explanationEs: "Usá \"is\" con sujetos en tercera persona singular (he, she, it, Link). \"Are\" es para sujetos plurales, y \"am\" solo va con \"I\".",
    },
  },
  {
    id: "vg-a1-wo",
    type: "word-order",
    tematica: "videojuegos",
    difficulty: "A1",
    categoryContext: "Pokémon",
    grammarTopic: "Basic sentence structure (SVO)",
    instruction: "Ordena las palabras para formar una oración correcta:",
    shuffledWords: ["Pikachu", "is", "yellow", "a", "Pokémon"],
    correctOrder: ["Pikachu", "is", "a", "yellow", "Pokémon"],
    spanishTranslation: "Pikachu es un Pokemon amarillo.",
tip: {
      title: "Subject + Verb + Object/Complement",
      explanation:
        "English follows Subject-Verb-Object order. 'Pikachu' (subject) + 'is' (verb) + 'a yellow Pokémon' (complement).",
      titleEs: "Sujeto + Verbo + Complemento",
      explanationEs: "El inglés sigue el orden Sujeto-Verbo-Objeto. \"Pikachu\" (sujeto) + \"is\" (verbo) + \"a yellow Pokémon\" (complemento).",
    },
  },
  {
    id: "vg-a1-rc",
    type: "reading-comprehension",
    tematica: "videojuegos",
    difficulty: "A1",
    categoryContext: "Super Mario",
    grammarTopic: "Personal Pronouns",
    instruction: "Lee el texto y responde la pregunta:",
    passage:
      "Mario is a plumber from Italy. He wears red clothes and a red hat. His brother is Luigi. Luigi wears green clothes.",
    questionText: "What color does Mario wear?",
    options: ["Green", "Red", "Blue", "Yellow"],
    correctIndex: 1,
    tip: {
      title: "Reading for Key Details",
      explanation:
        "The text says 'He wears red clothes'. When asked about a specific detail, look for keywords in the passage.",
      titleEs: "Lectura de detalles clave",
      explanationEs: "El texto dice \"He wears red clothes\". Cuando te pregunten por un detalle específico, buscá las palabras clave en el pasaje.",
    },
  },
  {
    id: "vg-a1-qa",
    type: "question-answer",
    variant: "find-question",
    tematica: "videojuegos",
    difficulty: "A1",
    categoryContext: "Fortnite",
    grammarTopic: "Wh- questions",
    instruction: "Elige la pregunta que mejor corresponde a esta respuesta:",
    prompt: "The Battle Bus flies over the island.",
    options: [
      "What flies over the island?",
      "Who is on the island?",
      "Where is the Battle Bus?",
      "Why does it fly?",
    ],
    correctIndex: 0,
    tip: {
      title: "Wh- Questions with 'What'",
      explanation:
        "'What' asks about things or actions. The answer names a thing (the Battle Bus), so the question must use 'What'.",
      titleEs: "Preguntas con \"What\"",
      explanationEs: "\"What\" pregunta por cosas o acciones. La respuesta nombra una cosa (the Battle Bus), así que la pregunta debe usar \"What\".",
    },
  },

  // ===== A2 =====
  {
    id: "vg-a2-mc",
    type: "multiple-choice",
    tematica: "videojuegos",
    difficulty: "A2",
    categoryContext: "Minecraft",
    grammarTopic: "Present Simple (3rd person)",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "Every day, Steve ___ wood from trees and ___ structures to survive.",
    options: [
      "chops / builds",
      "chop / build",
      "is chopping / building",
      "has chopped / built",
    ],
    correctIndex: 0,
    tip: {
      title: "Present Simple — Third Person",
      explanation:
        "In present simple, third-person singular (he/she/it/Steve) adds -s to the verb. 'Every day' signals a habitual routine.",
      titleEs: "Presente simple — tercera persona",
      explanationEs: "En presente simple, la tercera persona singular (he/she/it/Steve) agrega -s al verbo. \"Every day\" indica una rutina habitual.",
    },
  },
  {
    id: "vg-a2-wo",
    type: "word-order",
    tematica: "videojuegos",
    difficulty: "A2",
    categoryContext: "Final Fantasy VII",
    grammarTopic: "Present Continuous",
    instruction: "Ordena las palabras para formar una oración correcta:",
    shuffledWords: [
      "Cloud",
      "is",
      "fighting",
      "Sephiroth",
      "right",
      "now",
    ],
    correctOrder: ["Cloud", "is", "fighting", "Sephiroth", "right", "now"],
    spanishTranslation: "Cloud esta luchando contra Sephiroth ahora mismo.",
tip: {
      title: "Present Continuous Structure",
      explanation:
        "Subject + be + verb-ing + object + time expression. 'Right now' typically goes at the end of the sentence.",
      titleEs: "Estructura del presente continuo",
      explanationEs: "Sujeto + be + verbo-ing + objeto + expresión de tiempo. \"Right now\" suele ir al final de la oración.",
    },
  },
  {
    id: "vg-a2-rc",
    type: "reading-comprehension",
    tematica: "videojuegos",
    difficulty: "A2",
    categoryContext: "The Legend of Zelda",
    grammarTopic: "Can / Can't",
    instruction: "Lee el texto y responde:",
    passage:
      "In Breath of the Wild, Link can climb almost any surface. He can also cook food to restore hearts. However, he cannot swim in cold water without special equipment. He can use a paraglider to travel across the map.",
    questionText: "What can Link NOT do in cold water?",
    options: ["Climb", "Cook", "Swim", "Fly"],
    correctIndex: 2,
    tip: {
      title: "Understanding 'cannot' in Context",
      explanation:
        "The text says 'he cannot swim in cold water'. 'Cannot' means it is not possible. The answer is what he CANNOT do, not what he CAN do.",
      titleEs: "Entendiendo \"cannot\" en contexto",
      explanationEs: "El texto dice \"he cannot swim in cold water\". \"Cannot\" significa que no es posible. La respuesta es lo que NO puede hacer.",
    },
  },
  {
    id: "vg-a2-qa",
    type: "question-answer",
    variant: "find-answer",
    tematica: "videojuegos",
    difficulty: "A2",
    categoryContext: "Among Us",
    grammarTopic: "Short answers",
    instruction: "Elige la mejor respuesta para esta pregunta:",
    prompt: "Is the red character the impostor?",
    options: [
      "Yes, he is the impostor.",
      "No, he doesn't like red.",
      "Yes, he can be red.",
      "No, he is in the game.",
    ],
    correctIndex: 0,
    tip: {
      title: "Yes/No Short Answers",
      explanation:
        "A proper answer to 'Is...?' uses 'Yes, [subject] is...' or 'No, [subject] isn't...'. The answer must match the question logically.",
      titleEs: "Respuestas cortas de sí/no",
      explanationEs: "Una respuesta adecuada a \"Is...?\" usa \"Yes, [sujeto] is...\" o \"No, [sujeto] isn't...\". La respuesta debe coincidir lógicamente con la pregunta.",
    },
  },

  // ===== B1 =====
  {
    id: "vg-b1-mc",
    type: "multiple-choice",
    tematica: "videojuegos",
    difficulty: "B1",
    categoryContext: "The Last of Us",
    grammarTopic: "Past Simple",
    instruction: "Selecciona la opción correcta:",
    sentence: "Joel ___ across the country with Ellie last year.",
    options: ["traveled", "was traveling", "had traveled", "travels"],
    correctIndex: 0,
    tip: {
      title: "Past Simple for Completed Actions",
      explanation:
        "Past simple describes completed actions in the past. 'Last year' signals a finished time period, requiring past simple.",
      titleEs: "Pasado simple para acciones completadas",
      explanationEs: "El pasado simple describe acciones terminadas en el pasado. \"Last year\" señala un período de tiempo finalizado.",
    },
  },
  {
    id: "vg-b1-wo",
    type: "word-order",
    tematica: "videojuegos",
    difficulty: "B1",
    categoryContext: "Undertale",
    grammarTopic: "Past Simple questions",
    instruction: "Ordena las palabras para formar una pregunta correcta:",
    shuffledWords: [
      "did",
      "the",
      "player",
      "choose",
      "the",
      "pacifist",
      "route",
      "?",
    ],
    correctOrder: [
      "did",
      "the",
      "player",
      "choose",
      "the",
      "pacifist",
      "route",
      "?",
    ],
    spanishTranslation: "El jugador eligio la ruta pacifista?",
tip: {
      title: "Past Simple Questions with 'Did'",
      explanation:
        "For past simple questions, use 'Did + subject + base verb'. The auxiliary 'did' carries the past tense, so the main verb stays in base form.",
      titleEs: "Preguntas en pasado simple con \"Did\"",
      explanationEs: "Para preguntas en pasado simple, usá \"Did + sujeto + verbo base\". El auxiliar \"did\" lleva el tiempo pasado.",
    },
  },
  {
    id: "vg-b1-rc",
    type: "reading-comprehension",
    tematica: "videojuegos",
    difficulty: "B1",
    categoryContext: "Stardew Valley",
    grammarTopic: "Used to",
    instruction: "Lee el texto y responde:",
    passage:
      "Before moving to Stardew Valley, the farmer used to work in a big office at Joja Corporation. He used to spend all day at a desk, and he didn't use to see the sun very often. Now he grows crops, raises animals, and talks to villagers every day. His life is completely different now.",
    questionText: "What did the farmer use to do before Stardew Valley?",
    options: [
      "Grow crops",
      "Raise animals",
      "Work in an office",
      "Talk to villagers",
    ],
    correctIndex: 2,
    tip: {
      title: "'Used to' for Past Habits",
      explanation:
        "'Used to' describes past habits or states that are no longer true. The text says 'used to work in a big office', which contrasts with his current farm life.",
      titleEs: "\"Used to\" para hábitos pasados",
      explanationEs: "\"Used to\" describe hábitos o estados pasados que ya no son ciertos. El texto dice \"used to work in a big office\", contrastando con su vida actual en la granja.",
    },
  },
  {
    id: "vg-b1-qa",
    type: "question-answer",
    variant: "find-question",
    tematica: "videojuegos",
    difficulty: "B1",
    categoryContext: "Portal",
    grammarTopic: "How questions",
    instruction: "Elige la pregunta que mejor corresponde a esta respuesta:",
    prompt: "Chell solved the test chambers by using the portal gun.",
    options: [
      "How did Chell solve the test chambers?",
      "Why did Chell solve the test chambers?",
      "When did Chell solve the test chambers?",
      "Who solved the test chambers?",
    ],
    correctIndex: 0,
    tip: {
      title: "Questions with 'How'",
      explanation:
        "'How' asks about the method or manner. The answer explains the method (by using the portal gun), so the question must use 'How'.",
      titleEs: "Preguntas con \"How\"",
      explanationEs: "\"How\" pregunta por el método o la manera. La respuesta explica el método (by using the portal gun), así que la pregunta debe usar \"How\".",
    },
  },

  // ===== B2 =====
  {
    id: "vg-b2-mc",
    type: "multiple-choice",
    tematica: "videojuegos",
    difficulty: "B2",
    categoryContext: "Pokémon",
    grammarTopic: "Present Perfect",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "Ash ___ Pokémon since he was ten years old, and he ___ the championship yet.",
    options: [
      "has trained / hasn't won",
      "trained / didn't win",
      "has been training / wasn't winning",
      "trains / doesn't win",
    ],
    correctIndex: 0,
    tip: {
      title: "Present Perfect — Duration + Yet",
      explanation:
        "Use present perfect for an action that started in the past and continues now (has trained). 'Yet' in negative sentences means 'up to now'.",
      titleEs: "Presente perfecto — duración + \"yet\"",
      explanationEs: "Usá presente perfecto para una acción que empezó en el pasado y continúa ahora (has trained). \"Yet\" en oraciones negativas significa \"hasta ahora\".",
    },
  },
  {
    id: "vg-b2-wo",
    type: "word-order",
    tematica: "videojuegos",
    difficulty: "B2",
    categoryContext: "Super Mario",
    grammarTopic: "First Conditional",
    instruction: "Ordena las palabras para formar una oración correcta:",
    shuffledWords: [
      "If",
      "Mario",
      "collects",
      "a",
      "Super",
      "Star",
      "he",
      "will",
      "become",
      "invincible",
    ],
    correctOrder: [
      "If",
      "Mario",
      "collects",
      "a",
      "Super",
      "Star",
      "he",
      "will",
      "become",
      "invincible",
    ],
    spanishTranslation: "Si Mario agarra una Super Estrella se volvera invencible.",
tip: {
      title: "First Conditional Word Order",
      explanation:
        "If + present simple, will + base verb. The 'if' clause comes first, followed by a comma, then the 'will' clause.",
      titleEs: "Orden de palabras en el primer condicional",
      explanationEs: "If + presente simple, will + verbo base. La cláusula \"if\" va primero, seguida de una coma, luego la cláusula con \"will\".",
    },
  },
  {
    id: "vg-b2-rc",
    type: "reading-comprehension",
    tematica: "videojuegos",
    difficulty: "B2",
    categoryContext: "Dark Souls",
    grammarTopic: "Despite / In spite of",
    instruction: "Lee el texto y responde:",
    passage:
      "Despite its brutal difficulty, Dark Souls became one of the most influential games of the 2010s. Players die hundreds of times, but they keep coming back. In spite of having no difficulty settings or clear map markers, the game rewards patience and careful observation. Many games have since copied its mechanics, though few have captured its sense of accomplishment.",
    questionText:
      "According to the text, why do players keep playing Dark Souls?",
    options: [
      "Because it has difficulty settings",
      "Because it rewards patience and observation",
      "Because it has clear map markers",
      "Because it is easy to play",
    ],
    correctIndex: 1,
    tip: {
      title: "Understanding 'Despite' and 'In spite of'",
      explanation:
        "'Despite' and 'in spite of' introduce a contrast. The text says the game is difficult, BUT it rewards patience. The question asks for the reason players continue.",
      titleEs: "Entendiendo \"Despite\" e \"In spite of\"",
      explanationEs: "\"Despite\" e \"in spite of\" introducen un contraste. El texto dice que el juego es difícil, PERO recompensa la paciencia.",
    },
  },
  {
    id: "vg-b2-qa",
    type: "question-answer",
    variant: "find-answer",
    tematica: "videojuegos",
    difficulty: "B2",
    categoryContext: "Grand Theft Auto V",
    grammarTopic: "Giving opinions",
    instruction: "Elige la mejor respuesta para esta pregunta:",
    prompt:
      "Do you think GTA V is still worth playing in 2026?",
    options: [
      "Absolutely — the open world and storytelling hold up remarkably well even after all these years.",
      "I played it once.",
      "It was made by Rockstar.",
      "The game has three main characters.",
    ],
    correctIndex: 0,
    tip: {
      title: "Opinion Responses",
      explanation:
        "When asked for an opinion ('Do you think...'), respond with your view and support it with reasons. Factual statements without opinion don't answer the question.",
      titleEs: "Respuestas de opinión",
      explanationEs: "Cuando te pregunten por una opinión (\"Do you think...\"), respondé con tu punto de vista y respaldalo con razones.",
    },
  },

  // ===== C1 =====
  {
    id: "vg-c1-mc",
    type: "multiple-choice",
    tematica: "videojuegos",
    difficulty: "C1",
    categoryContext: "Dark Souls",
    grammarTopic: "Past Perfect",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "By the time the Chosen Undead reached Anor Londo, Gwyn ___ the First Flame.",
    options: [
      "had already linked",
      "already linked",
      "has already linked",
      "was already linking",
    ],
    correctIndex: 0,
    tip: {
      title: "Past Perfect — Sequence of Events",
      explanation:
        "Past perfect (had + past participle) shows an action completed before another past action. Gwyn linked the flame BEFORE the Chosen Undead arrived.",
      titleEs: "Pasado perfecto — secuencia de eventos",
      explanationEs: "El pasado perfecto (had + participio) muestra una acción completada antes que otra acción pasada. Gwyn vinculó la llama ANTES de que el No Muerto Elegido llegara.",
    },
  },
  {
    id: "vg-c1-wo",
    type: "word-order",
    tematica: "videojuegos",
    difficulty: "C1",
    categoryContext: "Final Fantasy VII",
    grammarTopic: "Passive Voice",
    instruction: "Ordena las palabras para formar una oración en voz pasiva:",
    shuffledWords: [
      "Midgar",
      "was",
      "built",
      "by",
      "the",
      "Shinra",
      "Company",
    ],
    correctOrder: [
      "Midgar",
      "was",
      "built",
      "by",
      "the",
      "Shinra",
      "Company",
    ],
    spanishTranslation: "Midgar fue construida por la Compania Shinra.",
tip: {
      title: "Passive Voice Structure",
      explanation:
        "Passive: Subject + be + past participle + (by + agent). The focus is on Midgar (what was built), not on Shinra (who built it).",
      titleEs: "Estructura de la voz pasiva",
      explanationEs: "Pasiva: Sujeto + be + participio pasado + (by + agente). El foco está en Midgar (lo construido), no en Shinra (quién lo construyó).",
    },
  },
  {
    id: "vg-c1-rc",
    type: "reading-comprehension",
    tematica: "videojuegos",
    difficulty: "C1",
    categoryContext: "BioShock",
    grammarTopic: "Inference and Implication",
    instruction: "Lee el texto y responde:",
    passage:
      "Andrew Ryan built Rapture as a utopia where the artist would not fear the censor, where the scientist would not be bound by petty morality. Yet beneath the art deco beauty and neon glow, something had gone terribly wrong. Splicers roamed the corridors, addicted to ADAM, their humanity eroded plasmid by plasmid. The city that was meant to elevate mankind had instead reduced it to its most primitive state.",
    questionText:
      "What does the author imply about Rapture's failure?",
    options: [
      "The city ran out of electricity",
      "Absolute freedom without ethics led to chaos and destruction",
      "The architecture was poorly designed",
      "The citizens simply got bored and left",
    ],
    correctIndex: 1,
    tip: {
      title: "Making Inferences",
      explanation:
        "The text contrasts the idealistic vision ('no petty morality') with the horrific result ('humanity eroded'). The implication is that unlimited freedom, unchecked by ethics, caused the collapse.",
      titleEs: "Haciendo inferencias",
      explanationEs: "El texto contrasta la visión idealista (\"sin moralidad mezquina\") con el resultado horrible (\"humanidad erosionada\"). La implicación es que la libertad sin límites causó el colapso.",
    },
  },
  {
    id: "vg-c1-qa",
    type: "question-answer",
    variant: "find-question",
    tematica: "videojuegos",
    difficulty: "C1",
    categoryContext: "Shadow of the Colossus",
    grammarTopic: "Complex question formation",
    instruction: "Elige la pregunta que mejor corresponde a esta respuesta:",
    prompt:
      "Wander destroyed the colossi because he believed it would bring Mono back to life.",
    options: [
      "What motivated Wander to destroy the colossi?",
      "How many colossi did Wander destroy?",
      "Where did Wander find the colossi?",
      "When did Wander destroy the colossi?",
    ],
    correctIndex: 0,
    tip: {
      title: "Questions about Motivation",
      explanation:
        "When the answer explains a reason or motivation (because he believed...), the question should ask 'What motivated...' or 'Why did...'",
      titleEs: "Preguntas sobre motivación",
      explanationEs: "Cuando la respuesta explica una razón o motivación (because he believed...), la pregunta debe preguntar \"What motivated...\" o \"Why did...\"",
    },
  },

  // ===== C2 =====
  {
    id: "vg-c2-mc",
    type: "multiple-choice",
    tematica: "videojuegos",
    difficulty: "C2",
    categoryContext: "Undertale",
    grammarTopic: "Mixed Conditionals",
    instruction: "Selecciona la opción correcta:",
    sentence:
      "If the player ___ the pacifist route, they ___ a different ending right now.",
    options: [
      "hadn't chosen / would be seeing",
      "didn't choose / will see",
      "doesn't choose / would see",
      "hadn't chosen / saw",
    ],
    correctIndex: 0,
    tip: {
      title: "Mixed Conditionals — Past Condition, Present Result",
      explanation:
        "If + past perfect (past condition), would + base verb (present result). The choice happened in the past, but the consequence affects the present experience.",
      titleEs: "Condicionales mixtos — condición pasada, resultado presente",
      explanationEs: "If + pasado perfecto (condición pasada), would + verbo base (resultado presente). La elección ocurrió en el pasado, pero la consecuencia afecta la experiencia presente.",
    },
  },
  {
    id: "vg-c2-wo",
    type: "word-order",
    tematica: "videojuegos",
    difficulty: "C2",
    categoryContext: "The Last of Us Part II",
    grammarTopic: "Cleft sentences",
    instruction: "Ordena las palabras para formar una oración enfática (cleft sentence):",
    shuffledWords: [
      "It",
      "was",
      "Ellie's",
      "desire",
      "for",
      "revenge",
      "that",
      "drove",
      "the",
      "story",
      "forward",
    ],
    correctOrder: [
      "It",
      "was",
      "Ellie's",
      "desire",
      "for",
      "revenge",
      "that",
      "drove",
      "the",
      "story",
      "forward",
    ],
    spanishTranslation: "Fue el deseo de venganza de Ellie lo que impulso la historia.",
tip: {
      title: "Cleft Sentences for Emphasis",
      explanation:
        "'It was X that Y' emphasizes X. Here, the structure highlights Ellie's desire for revenge as the driving force, rather than using a simple sentence.",
      titleEs: "Oraciones enfáticas (cleft sentences)",
      explanationEs: "\"It was X that Y\" enfatiza X. Esta estructura resalta el deseo de venganza de Ellie como el motor de la historia.",
    },
  },
  {
    id: "vg-c2-rc",
    type: "reading-comprehension",
    tematica: "videojuegos",
    difficulty: "C2",
    categoryContext: "Death Stranding",
    grammarTopic: "Figurative Language",
    instruction: "Lee el texto y responde:",
    passage:
      "In Death Stranding, connecting America isn't merely a logistical challenge — it's a meditation on the ties that bind us. Each package delivered is a thread in a tapestry of human connection, woven across a fractured landscape. The game's central thesis is audacious: that the distance between people isn't measured in kilometers, but in the courage it takes to reach out. Kojima transforms the humble act of delivery into an allegory for the human condition — we are all, in some sense, porters carrying the weight of others' hopes across treacherous terrain.",
    questionText:
      "What does the 'fractured landscape' metaphorically represent?",
    options: [
      "The physical geography of America",
      "The broken relationships and isolation between people",
      "The damage caused by natural disasters",
      "The economic inequality across the country",
    ],
    correctIndex: 1,
    tip: {
      title: "Metaphor in Literary Analysis",
      explanation:
        "The 'fractured landscape' works on two levels: literal (the game's broken terrain) and metaphorical (divided human relationships). The passage's theme of 'connection' confirms the metaphorical reading.",
      titleEs: "Metáfora en análisis literario",
      explanationEs: "El \"paisaje fracturado\" funciona en dos niveles: literal (el terreno roto del juego) y metafórico (relaciones humanas divididas). El tema de \"conexión\" confirma la lectura metafórica.",
    },
  },
  {
    id: "vg-c2-qa",
    type: "question-answer",
    variant: "find-answer",
    tematica: "videojuegos",
    difficulty: "C2",
    categoryContext: "The Legend of Zelda",
    grammarTopic: "Nuanced opinion expression",
    instruction: "Elige la mejor respuesta para esta pregunta:",
    prompt:
      "Would you argue that Breath of the Wild fundamentally changed open-world game design?",
    options: [
      "Undoubtedly — its philosophy of 'if you can see it, you can reach it' and its systemic physics engine set a benchmark that the industry is still trying to match.",
      "Yes, it's a good game.",
      "I played it on the Nintendo Switch.",
      "The graphics are nice and the music is good.",
    ],
    correctIndex: 0,
    tip: {
      title: "Nuanced Argumentation in English",
      explanation:
        "At C2 level, answers should demonstrate sophisticated argumentation. The correct response uses specific terminology ('systemic physics engine'), references design philosophy, and makes a comparative claim about industry impact.",
      titleEs: "Argumentación matizada en inglés",
      explanationEs: "En nivel C2, las respuestas deben demostrar argumentación sofisticada. La respuesta correcta usa terminología específica y hace una afirmación comparativa sobre el impacto en la industria.",
    },
  },
];
